### ISSUE TITLE
["BUG"] FilterUserCourseEnrollmentsByTenant doesn't modify all needed views

### ISSUE THREAD

**Issue by JuanDavidBuitrago** [eduNEXT/edunext-platform#737]
**Describe the bug**
Views like `api/enrollment/v1/enrollments/` are not filtered correctly.

**To Reproduce**
0. Crea at least two organizations, each one associated to only one tenant, and enroll users to course belonging to those organizations.
1. Go to 'api/enrollment/v1/enrollments/' 
2. See all enrollment without filters

**Expected behavior**
FIlter enrollments using the current site.

**Additional context**
This is the view I found, but there might be others

**Comment by JuanDavidBuitrago** [comment]
@Ian2012 here is your reported issue.

**Comment by Ian2012** [comment]
@JuanDavidBuitrago is this a better place for this issue? 🤔

I forgot to mention that this issue is related to the TenantAwareCourseEnrollmentFilter defined on eox-core

**Comment by JuanDavidBuitrago** [comment]
FilterUserCourseEnrollmentsByTenant is associated with the location of the filter, but I will check it.

**Comment by santiagosuarezedunext** [comment]
I'm going to put this issue in prioritized and we'll do it when we attack FFI-8

**Comment by MaferMazu** [comment]
@Ian2012 @JuanDavidBuitrago, are you talking about this https://github.com/eduNEXT/edunext-platform/blob/master/openedx/core/djangoapps/enrollments/views.py#L623?

@Ian2012, do you remember what you did when you discovered this? To understand a use case.

**Comment by MaferMazu** [comment]
I talked with @Ian2012 about this card, and he is not having this problem anymore because he has not been using the feature recently. I will close this because he doesn't need to pursue this, and the description talked about `api/enrollment/v1/enrollments/` an API from the edx-platform but involved eox-core and tenant, which makes this issue unclear.

If someone has this problem or needs to pursue this, please feel free to reopen this issue or open a new one in the required repository.
